# Generated by Django 4.0.1 on 2022-01-19 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='debit',
        ),
        migrations.AddField(
            model_name='stock',
            name='creditDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 12, 36, 29, 46735)),
        ),
        migrations.AddField(
            model_name='stock',
            name='debitDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 12, 36, 29, 46703)),
        ),
    ]
