# Generated by Django 4.0.1 on 2022-01-19 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_stock_credit_remove_stock_debit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='creditDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 17, 29, 19, 486054)),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='debitDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 17, 29, 19, 486033)),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
