# Generated by Django 4.0.1 on 2022-01-19 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productinventory_creditdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='creditDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 21, 35, 49, 436168), help_text='format: required, YYYY-MM-DD HH:MN:SC (2022-01-19 17:29:19) '),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='debitDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 21, 35, 49, 436146), help_text='format: required, YYYY-MM-DD HH:MN:SC (2022-01-19 17:29:19) '),
        ),
    ]
